name: EdgarAI Appointments Auto-Complete Cron

on:
  schedule:
    # Ejecutar todos los días a las 6:00 AM hora de México (UTC-6)
    # En UTC sería las 12:00 (12:00 PM)
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  call-appointments-auto-complete-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call appointments auto-complete endpoint
        run: |
          curl -v "https://edgarai.vercel.app/api/appointments/auto-complete/" 