name: EdgarAI Appointments Auto-Complete Cron

on:
  schedule:
    # Ejecutar cada hora para procesar citas vencidas en lotes pequeños
    # En UTC sería cada hora en punto
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  call-appointments-auto-complete-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call appointments auto-complete endpoint
        run: |
          curl -v "https://edgarai.vercel.app/api/appointments/auto-complete/?limit=10" 