name: EdgarAI Cron Test

on:
  schedule:
    # Ejecuta cada 2 horas
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  call-cron-test-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron-test endpoint
        run: |
          curl -v "https://edgarai.vercel.app/api/cron-test/" 