name: EdgarAI Reminders Process Cron

on:
  schedule:
    # Ejecuta cada 5 minutos de 13:00 a 23:00 UTC (8am a 6pm México)
    - cron: '*/5 13-23 * * *'
  workflow_dispatch:

jobs:
  call-reminders-process-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call reminders process endpoint
        run: |
          curl -v "https://edgarai.vercel.app/api/reminders/process/" 