name: EdgarAI Reminders Process Cron

on:
  schedule:
    # Ejecuta cada 30 minutos (en los minutos 0 y 30 de cada hora UTC)
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  call-reminders-process-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call reminders process endpoint
        run: |
          curl -v "https://edgarai.vercel.app/api/reminders/process/?dealership_id=534e6d39-7cea-4182-b9ad-15b0f4997484&reminder_type=follow_up" 