name: EdgarAI Reminders Process Cron

on:
  schedule:
    # Ejecuta cada 10 minutos de 12:00 a 23:00 UTC (7am a 6pm México)
    - cron: '*/10 12-23 * * *'
  workflow_dispatch:

jobs:
  call-reminders-process-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call reminders process endpoint
        run: |
          curl -v "https://edgarai.vercel.app/api/reminders/process/" 