name: EdgarAI Reactivar Agentes AI

on:
  schedule:
    # Reactivar agentes todos los días a las 7:55 AM (Ciudad de México)
    - cron: '55 13 * * *'  # UTC-6 = 7:55 AM Ciudad de México
  workflow_dispatch:

jobs:
  call-reactivate-agents-endpoint-agency1:
    runs-on: ubuntu-latest
    steps:
      - name: Call reactivate agents endpoint - Agencia 1
        run: |
          curl -v -L -X POST "https://edgarai.vercel.app/api/cron/reactivate-agents/" \
            -H "Content-Type: application/json" \
            -d '{"dealership_id":"b8ecf479-16ed-4f38-a726-cc1617a1fcbf"}'

  call-reactivate-agents-endpoint-agency2:
    runs-on: ubuntu-latest
    needs: call-reactivate-agents-endpoint-agency1
    steps:
      - name: Call reactivate agents endpoint - Agencia 2
        run: |
          curl -v -L -X POST "https://edgarai.vercel.app/api/cron/reactivate-agents/" \
            -H "Content-Type: application/json" \
            -d '{"dealership_id":"6fa78291-c16a-4c78-9fe2-9e3695d24d48"}'

  call-reactivate-agents-endpoint-agency3:
    runs-on: ubuntu-latest
    needs: call-reactivate-agents-endpoint-agency2
    steps:
      - name: Call reactivate agents endpoint - Agencia 3
        run: |
          curl -v -L -X POST "https://edgarai.vercel.app/api/cron/reactivate-agents/" \
            -H "Content-Type: application/json" \
            -d '{"dealership_id":"534e6d39-7cea-4182-b9ad-15b0f4997484"}'
