name: EdgarAI Reminders Expire Cron

on:
  schedule:
    # Ejecutar a las 5, 6 y 7 AM hora de México (UTC-6)
    # En UTC sería las 11:00, 12:00 y 13:00
    - cron: '0 11,12,13 * * *'
  workflow_dispatch:

jobs:
  call-reminders-expire-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call reminders expire endpoint
        run: |
          curl -v "https://edgarai.vercel.app/api/reminders/expire/" 